//! File tags on the stream manifest, from bundled rules and git attributes.
use git2::{IndexAddOption, Repository, Signature, Time};
use serde_json::Value;
use std::fs;
use std::process::{Command, Output};
use tempfile::TempDir;

/// A repository with a working tree, plus a home directory holding git's
/// user-wide attributes file.
struct Fixture {
    dir: TempDir,
    repo: Repository,
}

impl Fixture {
    fn new() -> Self {
        let dir = tempfile::tempdir().unwrap();
        let repo = Repository::init(dir.path().join("repo")).unwrap();
        fs::create_dir_all(dir.path().join("home/.config/git")).unwrap();
        Self { dir, repo }
    }

    fn write(&self, path: &str, text: &str) {
        let path = self.dir.path().join("repo").join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, text).unwrap();
    }

    fn user_attributes(&self, text: &str) {
        fs::write(self.dir.path().join("home/.config/git/attributes"), text).unwrap();
    }

    fn commit(&self) -> String {
        let mut index = self.repo.index().unwrap();
        index.add_all(["*"], IndexAddOption::DEFAULT, None).unwrap();
        index.write().unwrap();
        let tree = self.repo.find_tree(index.write_tree().unwrap()).unwrap();
        let signature = Signature::new(
            "Fixture",
            "fixture@example.invalid",
            &Time::new(946684800, 0),
        )
        .unwrap();
        let parent = self
            .repo
            .head()
            .ok()
            .map(|head| head.peel_to_commit().unwrap());
        let parents: Vec<_> = parent.iter().collect();
        self.repo
            .commit(
                Some("HEAD"),
                &signature,
                &signature,
                "fixture\n",
                &tree,
                &parents,
            )
            .unwrap()
            .to_string()
    }

    fn run(&self, base: &str, head: &str) -> Output {
        let home = self.dir.path().join("home");
        Command::new(assert_cmd::cargo_bin!("diffr"))
            .arg("--repo")
            .arg(self.dir.path().join("repo"))
            .args([base, head, "--format", "ndjson"])
            .env("HOME", &home)
            .env("XDG_CONFIG_HOME", home.join(".config"))
            .env_remove("GIT_DIR")
            .output()
            .unwrap()
    }
}

fn records(output: &Output) -> Vec<Value> {
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout.clone())
        .unwrap()
        .lines()
        .map(|line| serde_json::from_str(line).unwrap())
        .collect()
}

fn path_of(file: &Value) -> &str {
    file.get("rhs").or_else(|| file.get("lhs")).unwrap()["path"]
        .as_str()
        .unwrap()
}

fn tags_of<'a>(records: &'a [Value], path: &str) -> Vec<&'a str> {
    let entry = records[0]["files"]
        .as_array()
        .unwrap()
        .iter()
        .find(|entry| path_of(&entry["file"]) == path)
        .unwrap_or_else(|| panic!("{path} is not in the manifest"));
    match entry.get("tags") {
        Some(tags) => tags
            .as_array()
            .unwrap()
            .iter()
            .map(|tag| tag.as_str().unwrap())
            .collect(),
        None => Vec::new(),
    }
}

fn fallback_of<'a>(records: &'a [Value], path: &str) -> Option<&'a str> {
    let record = records
        .iter()
        .find(|record| record["type"] == "file" && path_of(&record["file"]) == path)
        .unwrap_or_else(|| panic!("{path} has no file record"));
    record["diff"]["stats"]
        .get("fallback")
        .map(|fallback| fallback["code"].as_str().unwrap())
}

#[test]
fn manifest_tags_follow_rules_then_attributes() {
    let fixture = Fixture::new();
    let lock = "[[package]]\nname = \"a\"\nversion = \"1.0.0\"\n";
    let go = "package api\n\nfunc A() int {\n\treturn 1\n}\n";
    fixture.write("Cargo.lock", lock);
    fixture.write("locks/Cargo.lock", lock);
    fixture.write("api/service.go", go);
    fixture.write("src/lib.rs", "fn a() -> u32 {\n    1\n}\n");
    fixture.write("tests/check.py", "def test_a():\n    assert 1\n");
    fixture.write("web/schema.json", "{\"a\": 1}\n");
    fixture.write("user.txt", "one\n");
    fixture.write("README.md", "# a\n");
    fixture.write(
        ".gitattributes",
        "locks/Cargo.lock linguist-generated=false\nweb/schema.json diffr-tags=schema,api\n",
    );
    fixture.user_attributes("user.txt diffr-tags=from-user\n");
    let base = fixture.commit();

    let lock = lock.replace("1.0.0", "1.1.0");
    fixture.write("Cargo.lock", &lock);
    fixture.write("locks/Cargo.lock", &lock);
    fixture.write(
        "api/service.go",
        &format!(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\n{}",
            go.replace('1', "2")
        ),
    );
    fixture.write("src/lib.rs", "fn a() -> u32 {\n    2\n}\n");
    fixture.write("tests/check.py", "def test_a():\n    assert 2\n");
    fixture.write("web/schema.json", "{\"a\": 2}\n");
    fixture.write("user.txt", "two\n");
    fixture.write("README.md", "# b\n");
    let head = fixture.commit();

    let records = records(&fixture.run(&base, &head));
    assert_eq!(tags_of(&records, "Cargo.lock"), vec!["generated"]);
    assert_eq!(tags_of(&records, "locks/Cargo.lock"), Vec::<&str>::new());
    assert_eq!(tags_of(&records, "api/service.go"), vec!["generated"]);
    assert_eq!(tags_of(&records, "src/lib.rs"), Vec::<&str>::new());
    assert_eq!(tags_of(&records, "tests/check.py"), vec!["test"]);
    assert_eq!(tags_of(&records, "web/schema.json"), vec!["api", "schema"]);
    assert_eq!(tags_of(&records, "user.txt"), vec!["from-user"]);
    assert_eq!(tags_of(&records, "README.md"), vec!["docs"]);

    assert_eq!(fallback_of(&records, "Cargo.lock"), Some("generated"));
    assert_eq!(fallback_of(&records, "api/service.go"), Some("generated"));
    assert_ne!(fallback_of(&records, "locks/Cargo.lock"), Some("generated"));
    assert_eq!(fallback_of(&records, "src/lib.rs"), None);
}

#[test]
fn a_malformed_diffr_tags_attribute_names_the_path() {
    let fixture = Fixture::new();
    fixture.write("bad.txt", "one\n");
    fixture.write(".gitattributes", "bad.txt diffr-tags=Not,ok\n");
    let base = fixture.commit();
    fixture.write("bad.txt", "two\n");
    let head = fixture.commit();
    let output = fixture.run(&base, &head);
    assert_eq!(output.status.code(), Some(2));
    assert!(output.stdout.is_empty());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("bad.txt: diffr-tags=Not,ok"), "{stderr}");
}
