[languages.rust]
folds = '''
([
  (block "{" "}")
  (field_declaration_list "{" "}")
  (declaration_list "{" "}")
  (match_block "{" "}")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "body"))
([
  (array_expression "[" "]")
  (field_initializer_list "{" "}")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "collection"))
((use_declaration) @fold
  (#set! tag "import"))
([
  (line_comment)
  (block_comment)
] @fold
  (#set! tag "comment"))
([
  (string_literal)
  (raw_string_literal)
] @fold
  (#set! tag "string"))
((function_item attributes: (attributes (attribute_item) @_attribute) body: (block) @fold)
  (#match? @_attribute "test")
  (#offset! @fold 0 1 0 -1)
  (#set! tag "test"))
'''
context = '''
[
  (function_item body: (block "{" @context.final "}" @context.last))
  (impl_item body: (declaration_list "{" @context.final "}" @context.last))
  (mod_item body: (declaration_list "{" @context.final "}" @context.last))
  (struct_item body: (field_declaration_list "{" @context.final "}" @context.last))
] @context
[(for_expression) (loop_expression) (match_expression) (return_expression)] @context @context.last
(function_item body: (block (_expression) @context @context.last .))
'''

[languages.python]
folds = '''
((block) @fold
  (#set! tag "body"))
([
  (list "[" "]")
  (dictionary "{" "}")
  (set "{" "}")
  (tuple "(" ")")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "collection"))
((tuple) @fold (#not-match? @fold "^\\(") (#set! tag "collection"))
([
  (import_statement)
  (import_from_statement)
] @fold
  (#set! tag "import"))
((comment) @fold
  (#set! tag "comment"))
((string) @fold
  (#set! tag "string"))
(function_definition name: (identifier) @_name body: (block) @fold
  (#match? @_name "^test_") (#set! tag "test"))
'''
context = '''
[(function_definition ":" @context.final) (class_definition ":" @context.final)] @context
[(for_statement) (return_statement)] @context @context.last
'''

[languages.go]
folds = '''
([
  (block "{" "}")
  (field_declaration_list "{" "}")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "body"))
((literal_value "{" "}") @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "collection"))
((import_declaration) @fold
  (#set! tag "import"))
((comment) @fold
  (#set! tag "comment"))
([
  (raw_string_literal)
  (interpreted_string_literal)
] @fold
  (#set! tag "string"))
(function_declaration name: (identifier) @_name body: (block) @fold
  (#match? @_name "^Test") (#offset! @fold 0 1 0 -1) (#set! tag "test"))
'''
context = '''
[
  (function_declaration body: (block "{" @context.final "}" @context.last))
  (method_declaration body: (block "{" @context.final "}" @context.last))
] @context
[(for_statement) (expression_switch_statement) (return_statement)] @context @context.last
'''

[languages.javascript]
folds = '''
([
  (statement_block "{" "}")
  (class_body "{" "}")
  (switch_body "{" "}")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "body"))
([
  (object "{" "}")
  (array "[" "]")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "collection"))
((import_statement) @fold
  (#set! tag "import"))
((comment) @fold
  (#set! tag "comment"))
([
  (string)
  (template_string)
] @fold
  (#set! tag "string"))
'''
context = '''
[
  (function_declaration body: (statement_block "{" @context.final "}" @context.last))
  (method_definition body: (statement_block "{" @context.final "}" @context.last))
  (arrow_function body: (statement_block "{" @context.final "}" @context.last))
  (class_declaration body: (class_body "{" @context.final "}" @context.last))
] @context
[(for_statement) (switch_statement) (return_statement)] @context @context.last
((arrow_function body: (_) @context.end) @context
  (#offset! @context.end 0 1 0 0))
'''

[languages.javascriptjsx]
folds = '''
([
  (statement_block "{" "}")
  (class_body "{" "}")
  (switch_body "{" "}")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "body"))
([
  (object "{" "}")
  (array "[" "]")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "collection"))
((import_statement) @fold
  (#set! tag "import"))
((comment) @fold
  (#set! tag "comment"))
([
  (string)
  (template_string)
] @fold
  (#set! tag "string"))
'''
context = '''
[
  (function_declaration body: (statement_block "{" @context.final "}" @context.last))
  (method_definition body: (statement_block "{" @context.final "}" @context.last))
  (arrow_function body: (statement_block "{" @context.final "}" @context.last))
  (class_declaration body: (class_body "{" @context.final "}" @context.last))
] @context
[(for_statement) (switch_statement) (return_statement)] @context @context.last
((arrow_function body: (_) @context.end) @context
  (#offset! @context.end 0 1 0 0))
'''

[languages.typescript]
folds = '''
([
  (statement_block "{" "}")
  (class_body "{" "}")
  (switch_body "{" "}")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "body"))
([
  (object "{" "}")
  (array "[" "]")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "collection"))
((import_statement) @fold
  (#set! tag "import"))
((comment) @fold
  (#set! tag "comment"))
([
  (string)
  (template_string)
] @fold
  (#set! tag "string"))
'''
context = '''
[
  (function_declaration body: (statement_block "{" @context.final "}" @context.last))
  (method_definition body: (statement_block "{" @context.final "}" @context.last))
  (arrow_function body: (statement_block "{" @context.final "}" @context.last))
  (class_declaration body: (class_body "{" @context.final "}" @context.last))
] @context
[(for_statement) (switch_statement) (return_statement)] @context @context.last
((arrow_function body: (_) @context.end) @context
  (#offset! @context.end 0 1 0 0))
'''

[languages.typescripttsx]
folds = '''
([
  (statement_block "{" "}")
  (class_body "{" "}")
  (switch_body "{" "}")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "body"))
([
  (object "{" "}")
  (array "[" "]")
] @fold
  (#offset! @fold 0 1 0 -1)
  (#set! tag "collection"))
((import_statement) @fold
  (#set! tag "import"))
((comment) @fold
  (#set! tag "comment"))
([
  (string)
  (template_string)
] @fold
  (#set! tag "string"))
'''
context = '''
[
  (function_declaration body: (statement_block "{" @context.final "}" @context.last))
  (method_definition body: (statement_block "{" @context.final "}" @context.last))
  (arrow_function body: (statement_block "{" @context.final "}" @context.last))
  (class_declaration body: (class_body "{" @context.final "}" @context.last))
] @context
[(for_statement) (switch_statement) (return_statement)] @context @context.last
((arrow_function body: (_) @context.end) @context
  (#offset! @context.end 0 1 0 0))
'''

